src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255 , unique=true)
     */
    private $reference;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $precaution;

    /**
     * @var Category
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     */
    private $category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="float", scale=4, nullable=true)
     */
    private $poidDufruitAcheter;

    /**
     * @ORM\Column(type="float", scale=4, nullable=true)
     */
    private $poidDufruitepluches;

    /**
     * @ORM\Column(type="float",  scale=4, nullable=true)
     */
    private $PassageRaffiner;

    /**
     * @ORM\Column(type="float", scale=4, nullable=true)
     */
    private $nombreTamissage;

    /**
     * @ORM\Column(type="float", scale=4, nullable=true)
     */
    private $poidDuFruitTamisse;

    /**
     * @ORM\Column(type="float", scale=4,   nullable=true)
     */
    private $passageEmissionneuse;

    /**
     * @ORM\Column(type="float", scale=4, nullable=true)
     */
    private $QteEau;

    /**
     * @ORM\Column(type="float", scale=4, nullable=true)
     */
    private $poidFinal;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $MesurrPHAvant;

    /**
     * @ORM\Column(type="float",  scale=4,  nullable=true)
     */
    private $qteAcide;

    /**
     * @ORM\Column(type="float", scale=4,  nullable=true)
     */
    private $mesurePHApres;

    /**
     * @ORM\Column(type="float", scale=4,  nullable=true)
     */
    private $mesureBrix;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $qteSucre;

    /**
     * @ORM\Column(type="float", scale=3, nullable=true)
     */
    private $mesureBrixFinal;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbrBoiteProduite;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDelete;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CommandProduit", mappedBy="produit")
     */
    private $commandProduits;

    /**
     * @ORM\Column(type="integer")
     */
    private $initNombreproduit;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BarCode", mappedBy="produit")
     */
    private $barCodes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;


    public function __construct()
    {
        $this->isDelete = false;
        $this->commandProduits = new ArrayCollection();
        $this->barCodes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrecaution(): ?string
    {
        return $this->precaution;
    }

    public function setPrecaution(?string $precaution): self
    {
        $this->precaution = $precaution;

        return $this;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    public function setCategory(Category $category = null)
    {
        $this->category = $category;
        return $this;
    }

    public function addCategory(Category $category = null): self
    {
        $this->category = $category;
        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->category->contains($category)) {
            $this->category->removeElement($category);
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPoidDufruitAcheter(): ?float
    {
        return $this->poidDufruitAcheter;
    }

    public function setPoidDufruitAcheter(?float $poidDufruitAcheter): self
    {
        $this->poidDufruitAcheter = $poidDufruitAcheter;

        return $this;
    }

    public function getPoidDufruitepluches(): ?float
    {
        return $this->poidDufruitepluches;
    }

    public function setPoidDufruitepluches(?float $poidDufruitepluches): self
    {
        $this->poidDufruitepluches = $poidDufruitepluches;

        return $this;
    }

    public function getPassageRaffiner(): ?float
    {
        return $this->PassageRaffiner;
    }

    public function setPassageRaffiner(?float $PassageRaffiner): self
    {
        $this->PassageRaffiner = $PassageRaffiner;

        return $this;
    }

    public function getNombreTamissage(): ?float
    {
        return $this->nombreTamissage;
    }

    public function setNombreTamissage(?float $nombreTamissage): self
    {
        $this->nombreTamissage = $nombreTamissage;

        return $this;
    }

    public function getPoidDuFruitTamisse(): ?float
    {
        return $this->poidDuFruitTamisse;
    }

    public function setPoidDuFruitTamisse(?float $poidDuFruitTamisse): self
    {
        $this->poidDuFruitTamisse = $poidDuFruitTamisse;

        return $this;
    }

    public function getPassageEmissionneuse(): ?float
    {
        return $this->passageEmissionneuse;
    }

    public function setPassageEmissionneuse(?float $passageEmissionneuse): self
    {
        $this->passageEmissionneuse = $passageEmissionneuse;

        return $this;
    }

    public function getQteEau(): ?float
    {
        return $this->QteEau;
    }

    public function setQteEau(?float $QteEau): self
    {
        $this->QteEau = $QteEau;

        return $this;
    }

    public function getPoidFinal(): ?float
    {
        return $this->poidFinal;
    }

    public function setPoidFinal(?float $poidFinal): self
    {
        $this->poidFinal = $poidFinal;

        return $this;
    }

    public function getMesurrPHAvant(): ?float
    {
        return $this->MesurrPHAvant;
    }

    public function setMesurrPHAvant(?float $MesurrPHAvant): self
    {
        $this->MesurrPHAvant = $MesurrPHAvant;

        return $this;
    }

    public function getQteAcide(): ?float
    {
        return $this->qteAcide;
    }

    public function setQteAcide(?float $qteAcide): self
    {
        $this->qteAcide = $qteAcide;

        return $this;
    }

    public function getMesurePHApres(): ?float
    {
        return $this->mesurePHApres;
    }

    public function setMesurePHApres(?float $mesurePHApres): self
    {
        $this->mesurePHApres = $mesurePHApres;

        return $this;
    }

    public function getMesureBrix(): ?float
    {
        return $this->mesureBrix;
    }

    public function setMesureBrix(?float $mesureBrix): self
    {
        $this->mesureBrix = $mesureBrix;

        return $this;
    }

    public function getQteSucre(): ?float
    {
        return $this->qteSucre;
    }

    public function setQteSucre(?float $qteSucre): self
    {
        $this->qteSucre = $qteSucre;

        return $this;
    }

    public function getMesureBrixFinal(): ?float
    {
        return $this->mesureBrixFinal;
    }

    public function setMesureBrixFinal(?float $mesureBrixFinal): self
    {
        $this->mesureBrixFinal = (double) $mesureBrixFinal;

        return $this;
    }

    public function getNbrBoiteProduite(): ?int
    {
        return $this->nbrBoiteProduite;
    }

    public function setNbrBoiteProduite(?int $nbrBoiteProduite): self
    {
        $this->nbrBoiteProduite = $nbrBoiteProduite;

        return $this;
    }

    public function getIsDelete(): ?bool
    {
        return $this->isDelete;
    }

    public function setIsDelete(bool $isDelete): self
    {
        $this->isDelete = $isDelete;

        return $this;
    }

    /**
     * @return Collection|CommandProduit[]
     */
    public function getCommandProduits(): Collection
    {
        return $this->commandProduits;
    }

    public function addCommandProduit(CommandProduit $commandProduit): self
    {
        if (!$this->commandProduits->contains($commandProduit)) {
            $this->commandProduits[] = $commandProduit;
            $commandProduit->setProduit($this);
        }

        return $this;
    }

    public function removeCommandProduit(CommandProduit $commandProduit): self
    {
        if ($this->commandProduits->contains($commandProduit)) {
            $this->commandProduits->removeElement($commandProduit);
            // set the owning side to null (unless already changed)
            if ($commandProduit->getProduit() === $this) {
                $commandProduit->setProduit(null);
            }
        }

        return $this;
    }

    public function getInitNombreproduit(): ?int
    {
        return $this->initNombreproduit;
    }

    public function setInitNombreproduit(int $initNombreproduit): self
    {

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Common\ObjectManager;
use App\Entity\Produit;
use App\Factory\ProduitManagerStaticFactory;
use App\Form\Type\ProduitType;
use App\Managers\BonDeCommandeManager;
use App\Managers\PrintManager;
use App\Managers\ProduitManager;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\OptimisticLockException;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class ProduitController extends AbstractController
{
    private $pm;
    private $objectManager;
    /**
     * @var BonDeCommandeManager
     */
    private $commandeManager;

    public function __construct(
        ProduitManager $pm,
        ObjectManager $objectManager,
        BonDeCommandeManager $commandeManager)
    {
        $this->pm = $pm;
        $this->objectManager = $objectManager;
        $this->commandeManager = $commandeManager;
    }

    /**
     * @Route("/produit", name="produit", methods={"GET"}, options = { "expose" = true })
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request, PaginatorInterface $paginator)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $aoProduit = $this->pm->getAllProduct();
        if($request->query->get('query')) {
            $query = $request->query->get('query');
            $aoProduit = $this->pm->search($query);
        }


        $pagination = $paginator->paginate(
            $aoProduit, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            5 /*limit per page*/
        );
        return $this->render('produit/index.html.twig', [
            'titre' => 'Produits',
            'bande' => 'Produits',
            'produits' => $pagination,
        ]);
    }

    /**
     * @Route("/produit/ajouter", name="produit_add", methods={"POST","GET"})
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function addProduct(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $oProduit = new Produit();
        $form = $this->createForm(ProduitType::class, $oProduit);
        $form->handleRequest($request);
        //dump($form->getData()); die;
        if($form->isSubmitted() && $form->isValid()) {
            $oData = $form->getData();
            $aReturn = $this->pm->addProduct($oData);
            if($aReturn['code'] === 200) {
                $this->addFlash('success', 'Ajout Produit avec Succèss');
                return $this->redirectToRoute('produit');

            }
        }

        return $this->render('produit/add.html.twig', [
            'form' => $form->createView(),
            'titre' => 'Ajouter Produits',
            'bande' => 'Ajouter Produit',
            'routeParent' => 'produit',
            'routeNameParent' => 'Listes Produits',
        ]);
    }

    /**
     * @Route("produit/{id}", name="produit_view", methods={"GET"})
     * @param Request $request
     * @param $id
     * @return Response
     */
    public function viewProduct(Request $request, Produit $id )
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $oProduit = $id;
        return $this->render('produit/view.html.twig',[
            'titre' => 'Detail Produit',
            'bande' => 'detail produit',
            'routeParent' => 'produit',
            'routeNameParent' => 'Listes Produits',
            'produit' => $oProduit,
        ]);
    }

    /**
     * @Route("api/produit/{id}",
     *     name="api_produit_view",
     *     methods={"GET"},
     *     options = { "expose" = true }
     *     )
     * @param Produit $id
     * @param PrintManager $printManager
     * @return JsonResponse
     */
    public function apiProduitView(Produit $id, PrintManager $printManager)
    {
        $oProduit = $id;
        $aReturn =  $printManager->getPrint($oProduit);
        return new JsonResponse($aReturn);
    }

    /**
     * @Route(
     *     "produit/edit/{id}",
     *     name="produit_edit",
     *     methods={"GET", "POST"},
     *     options = { "expose" = true }
     *     )
     * @param Produit $id
     * @param Request $request
     * @return Response
     */
    public function edit(Produit $id, Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $oProduit = $id;
        $form = $this->createForm(ProduitType::class, $oProduit);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $this->objectManager->saveObject($oProduit);
            return $this->redirectToRoute('produit');
        }
        return $this->render('produit/add.html.twig', [
            'form' => $form->createView(),
            'titre' => 'Ajouter Produits',
            'bande' => 'Ajouter Produit',
            'routeParent' => 'produit',
            'routeNameParent' => 'Listes Produits',
        ]);
    }

    /**
     * @Route(
     *     "produit/delete/{id}",
     *     name="produit_delete",
     *     methods={"DELETE"},
     *     options={"expose" = true}
     * )
     * @param Produit $id
     * @return JsonResponse
     */
    public function delete(Produit $id)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $oProduit = $id;
        $aResponse = $this->pm->delete($oProduit);
        return new JsonResponse($aResponse);
    }

    /**
     * @Route(
     *     "/api/produits",
     *     name="api_produits_liste",
     *     methods={"GET"},
     *     options={"expose" = true}
     * )
     * @return JsonResponse
     */
    public function getStatProduitsAndCommand()
    {
        $aResponse = [];
        $aoProduit = $this->pm->getStatProduits();
        $aoCommand = $this->commandeManager->getStatCommand();
        $aResponse['produit'] = $aoProduit;
        $aResponse['command'] = $aoCommand;
        return new JsonResponse($aResponse);
    }

    /**
     * @Route(
     *     "/api/produits/listes",
     *     name="api_produits_listes_json",
     *     methods={"GET"},
     *     options={"expose" = true}
     * )
     * @return JsonResponse
     */
    public function getProduitWithAjax()
    {
        $aoProduit = $this->pm->getProduits();
        return new JsonResponse($aoProduit);
    }
}

templates/produit/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Detail Produit</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted">Nombre de boites Produictions</span>
                                        <span class="info-box-number text-center text-muted mb-0">{{ produit.nbrBoiteProduite }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted">Nombre de Tamissage</span>
                                        <span class="info-box-number text-center text-muted mb-0">{{ produit.nombreTamissage }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted">Poid des Fruit Achetés [kg]</span>
                                        <span class="info-box-number text-center text-muted mb-0">20 </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <table class="table table-bordered " >
                                    <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>Nom</th>
                                        <th style="width: 100px">Valeur</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1.</td>
                                        <td>Poids des Fruits achetés [kg]</td>
                                        <td>
                                            <span class="badge bg-info">
                                                {{ produit.poidDufruitAcheter }} Kg
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>2.</td>
                                        <td>Poids des Fruits épluchés [kg]</td>
                                        <td><span class="badge bg-info">{{ produit.poidDufruitepluches }} Kg</span></td>
                                    </tr>
                                    <tr>
                                        <td>3.</td>
                                        <td>Passage Raffineuse</td>
                                        <td><span class="badge bg-info">{{ produit.passageRaffiner }}</span></td>
                                    </tr>
                                    <tr>
                                        <td>4.</td>
                                        <td>Nombre de Tamisage</td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.nombreTamissage }} </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>5.</td>
                                        <td>Poids des Fruits Tamissée [kg] </td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.poidDuFruitTamisse }} Kg</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>6.</td>
                                        <td>Passage Emuisionneuse </td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.passageEmissionneuse }}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>7.</td>
                                        <td>Quantité d'eau Ajoutée [litres] </td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.qteEau }} L</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>8.</td>
                                        <td>Poids Final [Kg] </td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.poidFinal }} Kg</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>9.</td>
                                        <td>Mesure du PH Avant Traitement Acide Citrique</td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.mesurrPHAvant }}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>10.</td>
                                        <td>Quantité d'acide citrique rajouter [gr] </td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.qteAcide }} gr</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>11.</td>
                                        <td>Nouvelle Mesure du PH Après Traitement Acide</td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.mesurePHApres }}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>12.</td>
                                        <td>Mesure du Brix</td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.mesureBrix }}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>13.</td>
                                        <td>Quantité Sucre Ajouté [Kg]</td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.qteEau }} Kg</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>14.</td>
                                        <td>Mesure du Brix Final</td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.qteEau }}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>15.</td>
                                        <td>Nombre de boites Produites</td>
                                        <td>
                                            <span class="badge bg-info">{{ produit.qteEau }}</span>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
                        <h3 class="text-primary"><i class="fas fa-paint-brush"></i> {{ produit.name }}</h3>
                        <p class="text-muted">
                            {{ produit.description }}
                        </p>
                        <br>
                        <div class="text-muted">
                            <p class="text-sm">Production
                                <b class="d-block">{{ produit.category.name }}</b>
                            </p>
                            <p class="text-sm">Reference
                                <b class="d-block">{{ produit.reference }}</b>
                            </p>
                            <p class="text-sm">Date
                                <b class="d-block">{{ produit.createdAt | date('d/m/Y') }}</b>
                            </p>
                        </div>
                        <h5 class="mt-5 text-muted">Actions</h5>
                        <div class="mt-1 mb-3">
                            <a href="#" data-id="{{ produit.id }}" data-title="{{ produit.name }}" class="btn btn-sm btn-default printProduit" >
                                <i class="fas fa-print"></i>
                                Imprimer
                            </a>
                            <a href="#" data-id="{{ produit.id }}"  class="btn btn-sm btn-default">
                                <i class="fas fa-file-export"></i>
                                Export Pdf
                            </a>
                        </div>
                        <div class="mt-1 mb-3">
                            <a href="{{ path('produit_edit', {id: produit.id}) }}"
                               data-id=""  class="btn btn-sm btn-default">
                                <i class="fas fa-edit"></i>
                                Editer
                            </a>
                            <a href="#" data-id="{{ produit.id }}"  class="btn btn-sm btn-danger deleteProduit">
                                <i class="fas fa-trash "></i>
                                Supprimer
                            </a>
                        </div>

                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>

{% endblock %}